### ISSUE TITLE
Cannot use package

### ISSUE THREAD

**Issue by blacksmithop** [dsblank/picopipe#1]
**Platform**: Google Colab
**Version**: Python 3.10.12

### Issue
I am unable to use the package despite it being installed

![image](https://github.com/dsblank/picopipe/assets/60320192/e34e824e-715d-446e-8df4-9f66d865284f)

As you can see I tried installing the package from pip as well as the release zip file
![image](https://github.com/dsblank/picopipe/assets/60320192/e997eaa2-f3fc-4a33-9698-7c458ff87bef)

**Comment by dsblank** [comment]
Oh, thanks for the note! I forgot to actually include picopipe in the package. Should work now:

```
%pip install picopipe==1.0.2
```
![Screenshot from 2023-11-29 08-43-05](https://github.com/dsblank/picopipe/assets/168568/4f696cc7-b086-46dd-98f8-ca44c3243b81)

**Comment by dsblank** [comment]
Fixed with 96ca1d6e2bf113ab3e19e8077839ed10a46e99f4

Thanks! Closing this issue.
